name: Delete MongoDB on PR close

on:
  workflow_dispatch:

jobs:
  delete-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete database
        run: |
          wget https://fastdl.mongodb.org/linux/mongodb-shell-linux-x86_64-ubuntu2004-6.0.5.tgz
          tar -xvf mongodb-shell-linux-x86_64-ubuntu2004-6.0.5.tgz
          export PATH=$PWD/mongodb-linux-x86_64-ubuntu2004-6.0.5/bin:$PATH
          mongo --version
          /usr/bin/mongo --version

        shell: bash
