name: Delete MongoDB on PR close

on:
  workflow_dispatch:

jobs:
  delete-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete database
        run: |
          wget https://downloads.mongodb.com/compass/mongosh-2.3.4-linux-x64.tgz
          tar -xvf mongosh-2.3.4-linux-x64.tgz
          export PATH=$PWD/mongosh-2.3.4-linux-x64/bin:$PATH
          mongosh --version

        shell: bash
